[greeter]
background=/usr/share/backgrounds/lyra/2702-dawn.png
theme-name=Lyra-OS
icon-theme-name=Lyra-OS-Icons
font-name=Noto Sans 11
logo=/usr/share/icons/hicolor/scalable/apps/lyra-launcher.svg
hide-user-image=true
indicators=~host;~spacer;~clock;~spacer;~language;~session;~power
