[release]
version = "1.0"
base_distribution = "opensuse-leap"
base_version = "16.1"
stage = "alpha"
iteration = 7
codename = "Odisseia"
codename_id = "odisseia"
image_name = "LyraOS-Desktop-XFCE"
architecture = "x86_64"
