[greeter]
background=/usr/share/backgrounds/lyra/lyra-dawn.png
theme-name=Lyra-OS
icon-theme-name=Lyra-OS-Icons
font-name=Noto Sans 11
logo=/usr/share/icons/hicolor/scalable/apps/lyra-launcher.svg
default-user-image=/usr/share/icons/hicolor/scalable/apps/lyra-launcher.svg
hide-user-image=false
round-user-image=true
user-background=false
highlight-logged-user=true
position=50%,center 50%,center
active-monitor=#cursor
transition-duration=650
transition-type=ease-in-out
panel-position=top
clock-format=%A, %d de %B  •  %H:%M
indicators=~host;~spacer;~clock;~spacer;~a11y;~language;~layout;~session;~power
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
screensaver-timeout=60
